### ISSUE TITLE
Minor docs correction

### ISSUE THREAD

**Issue by Pjino** [promptworks/sans_password#1]
First let me thank you for this library.
I'm going through the docs trying to install it (also using Phoenix Framework) and I think that where you have:
`# web/views/session_controller.ex`
you mean:
`# web/controllers/session_controller.ex`

Also, instead of
`<!-- web/templates/new.html.eex -->`
you mean:
`<!-- web/templates/session/new.html.eex -->`

Finally, instead of
 `use Passwordles.Controller, view: MyApp.SessionView, hooks: __MODULE__`
you mean:
` use SansPassword.Controller, view: MyApp.SessionView, hooks: __MODULE__`
Thank you again!

**Comment by rzane** [comment]
You're absolutely right! Thanks for the corrections!

How is it working out for you? Any other issues?

**Comment by Pjino** [comment]
It was really easy to make it work, thank you.
Nevertheless I decided to try to implement a very basic authentication system based on Phoenix session just for the learning purposes, as I intend to use a third party library for real projects to avoid reinventing the wheel and for future consistency.
The only concern I have about using an authentication system without passwords is when using mobile. To me, it is not possible to use it as, for security reasons, I don't have any email client in my personal mobile. Most people use Gmail in their mobiles but also more and more realize that it tracks you and are leaving it for mobile...I don't know if this is something you ever heard of.
So, in mobile, other alternative communication systems is used instead.
But a great thank you, because you made using authentication a lot easy!
