### ISSUE TITLE
Plans for 1.0.0

### ISSUE THREAD

**Issue by morgz** [promptworks/sans_password#5]
Hi - Just wondering if there are any plans to get this out of Beta? Considering using it in a production app you see...

Thanks

Dan

**Comment by rzane** [comment]
Version 1.0.0 is actually on Hex, however the README hasn't been updated.

This library doesn't do much and is just a thin wrapper around Guardian, so the beta was only meant to capture that it was depending on a beta version of Guardian at that time.
