### ISSUE TITLE
Guardian 2.0

### ISSUE THREAD

**Issue by nathany** [promptworks/sans_password#6]
Any plans to update for Guardian 2.x?

**Comment by rzane** [comment]
When I originally wrote this package, this library was doing quite a lot. However, over the years, Guardian has added a lot of really helpful features. In doing so, it's made this library pretty much useless. At this point, this library is more or less just delegating to Guardian, providing convenient function names, and passing along `token_type` as an option.

I'd be happy to accept a PR, but honestly, I would probably recommend reading the source code here and implementing it in your own codebase. This repo would probably be more useful as an example app demonstrating how to implement passwordless authentication using Guardian.

**Comment by nathany** [comment]
Thanks for the reply.

I'm just adopting a project that was using Guardian 1.x and sans_password. Sounds like I should look into how to move it off. For now adding an override for guardian in mix.exs seems to be working.

**Comment by rzane** [comment]
Nice! Glad that worked. For what it's worth, to remove this library, I think you could remove the `use SansPassword` and replace it with:

```elixir
@magic "magic"
@access "access"

def encode_magic(resource, claims \\ %{}) do
  encode_and_sign(resource, claims, token_type: @magic)
end

def decode_magic(magic_token, claims \\ %{}) do
  resource_from_token(magic_token, claims, token_type: @magic)
end

def encode_access(resource, claims \\ %{}) do
  encode_and_sign(resource, claims, token_type: @access)
end

def decode_access(access_token, claims \\ %{}) do
  resource_from_token(access_token, claims, token_type: @access)
end

def exchange_magic(magic_token) do
  with {:ok, _, {token, claims}} <- exchange(magic_token, @magic, @access) do
    {:ok, token, claims}
  end
end

def send_magic_link(resource, claims \\ %{}, params \\ %{}) do
  with {:ok, magic_token, claims} <- encode_magic(resource, claims) do
    deliver_magic_link(resource, magic_token, params)
    {:ok, magic_token, claims}
  end
end
```
